name: cli
description: The CLI tool for QuadOS
publish_to: "none"
version: 1.0.0
repository: https://github.com/Quad-Linux/cli

environment:
    sdk: ^3.4.2

dev_dependencies:
    lints: ^3.0.0
dependencies:
    args: ^2.5.0
    io: ^1.0.4
