name: "Build Flatpak"
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v27
    - run: nix develop --command just flatpak-build
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: quad.flatpak
        path: build/quad.flatpak
